### ISSUE TITLE
App remains connected when another app connects to the same receiver app and start a media

### ISSUE THREAD

**Issue by Appostrophe** [googlecast/CastCompanionLibrary-android#228]
I feel like the expected behaviour would be that the first app either disconnects or update its media info in the VideoControllerActivity. None of these behaviours occurs

**Comment by naddaf** [comment]
You need to provide more information on what the two apps are.

**Comment by Appostrophe** [comment]
The receiver app is custom and we have the same  one sender app on Android and another on iOS

**Comment by naddaf** [comment]
I suggest test the CastVideos-android app from github, if the issue still
exists there with that app, then let me know.

**Comment by Appostrophe** [comment]
I cannot use the same app , this issue arise only when I use an Android and iOS app which use the same receiver.
It works perfectly when the same Android app or the same iOS app runs on two different devices.

**Comment by naddaf** [comment]
if it is the same app (that is using teh same app id), then it shouldn't disconnect. If two iOS apps work fine a d two android apps work fine but an iOS app and an Android app do not result in showing the correct updated media, then most likely the issue is in your senders; maybe they don't match on what fields you are using to populate the metadata. Anyhow, this is an issue on your side and is not related to CCL.
