### ISSUE TITLE
minSdkVersion - Change from 10 to 9

### ISSUE THREAD

**Issue by Brahmasmi** [googlecast/CastCompanionLibrary-android#246]
The current library uses a minSdkVersion of 10.
```
 minSdkVersion 10
```
(https://github.com/googlecast/CastCompanionLibrary-android/blob/master/build.gradle#L41)
```
 android:minSdkVersion="10"
```
(https://github.com/googlecast/CastCompanionLibrary-android/blob/master/AndroidManifest.xml#L22)
According to the Google Cast SDK documentation, the minSdkVersion supported is 9.
```
uses-sdk

The minimum Android SDK version that the Cast SDK supports is 9 (GingerBread).

<uses-sdk
        android:minSdkVersion="9"
        android:targetSdkVersion="19" />
```
(https://developers.google.com/cast/docs/android_sender#android-manifest)

The current library project builds successfully with minSdkVersion 9. Can we change the minSdkVersion from 10 to 9?

**Comment by naddaf** [comment]
If you have a need to support API level 9, you can make that change locally in your project otherwise I am not going to officially support that version; the number of devices is extremely low for that API level (it doesn't even show up on the dashboard) and even Ginger Bread is reaching a point that I expect in a few month I would drop support for that as well.
