### ISSUE TITLE
Notification disconnect action should not stop receiver application when multiple senders are connected

### ISSUE THREAD

**Issue by obec** [googlecast/CastCompanionLibrary-android#266]
Streps to reproduce:
1. Configure cast manager to have a disconnect action: addNotificationAction(addNotificationAction(CastConfiguration.NOTIFICATION_ACTION_DISCONNECT, true)
2. Connect Sender A to the cast device and begin playback.
3. Connect Sender B to the cast device.
4. Background both senders.
5. On Sender A, select the X to disconnect the device.

Expected: Sender A is disconnected but content continues playback. Sender B is still connected.
Actual: Both senders are disconnected and the receiver application is shutdown.

This differs from the behavior of the cast menu. However the wording in the design checklist could be taken either way. 
"Provide an "X" to stop casting and disconnect from the receiver, in the row of actions" - https://developers.google.com/cast/docs/design_checklist#sender-control-notification

That said, the section on how to handle when a sender disconnects/stops casting seems to cover both scenarios: https://developers.google.com/cast/docs/design_checklist#sender-control-end

If the ability to shutdown the receiver at any time from the notification is still desired, could we add a configuration option to select the behavior here?

**Comment by naddaf** [comment]
The current behavior,, which is stopping the receiver, is by design; the idea is that the user can use that to quickly shutdown the receiver; if they want to just disconnect, they can open the app and disconnect. 

The second link does not talk about this requirement and the first one states "stop casting and "disconnect" not just "disconnect". Again, this behavior is the intended behavior.

**Comment by obec** [comment]
Thank you for clearing that up.
