### ISSUE TITLE
VideoCastNotificationService shows STOP button for live streams instead of PAUSE, but triggers ACTION_TOGGLE_PLAYBACK intent instead of STOP

### ISSUE THREAD

**Issue by adrianrdzv** [googlecast/CastCompanionLibrary-android#268]
Hi,

I've noticed the VideoCastNotificationService has the configuration to show a pause button when buffered media is running, and a stop button when the stream is live. I believe this is correct.

The problem comes when you trigger the action, the intent that is started is the wrong one. A ACTION_TOGGLE_PLAYBACK is launched instead of an ACTION_STOP.

Of course with the new architecture of the VideoCastNotificationService we can override getPlayPauseAction to launch the correct intent, but just wondered if isn't this a bug in the implementation? Since a stop should trigger a stop. Not a pause.

**Comment by adrianrdzv** [comment]
I just realized that ACTION_STOP means STOP application, and not STOP stream. Why there is no playback STOP in the VideoIntentReceiver? I guess will have to create my own.

**Comment by adrianrdzv** [comment]
Another thing I noticed, the MediaRouteControllerDialog behaviour is inconsistent with the notification service behaviour. LIVE streams will show the pause button instead of stop.

**Comment by naddaf** [comment]
You would need to read the section Live Stream in the tutorial PDF doc to see how live streams are treated. In short, stopping a live stream, in many ways, is similar to pause but not quite. The "stop" action in SDK (vs pause or play) has a different meaning; when you call stop in SDK, it unloads the media and that is not what we want to happen for live stream; we kind of want to temporarily halt it but since there is no DVR, it doesn't pick up from where we stopped it but it continues with the current time. As a result, we need to call "pause" in SDK when we want to halt the stream but we need to interpret that differently and that is why receiver (which should be a custom one) needs to treat it a bit differently and send a different status update event. On the sender side, I show "stop" button instead of "pause" when stream is live but that is just a UI modification, otherwise sender, for the most part, considers that a pause (except for the event that it would expect to see from receiver). Hence, there is only one TOGGLE_PLAYBACK event from notification.

As for the MediaRouteControllerDialog, that is the stock dialog so I don't have any control over that to show a stop button.

**Comment by adrianrdzv** [comment]
I read the documentation in the PDF, it there it's explained the behaviour I comment on. I still think that even when "is just a UI modification", the UI should match the actual behaviour in the SDK.  Currently "stopping" a live stream from the notification, pauses it in the receiver app.

I don't see the benefit of changing the icon to stop, if there is no actual stop behaviour using it, and is inconsistent with other android components.

I would suggest to show always pause in that case, that way, pause will always match a pause action, even if it's a live stream, and the MediaRouteControllerDialog (which is obviously used together with the cast notification service most of the time) will behave the same way.

**Comment by naddaf** [comment]
As I said, halting a live stream is neither stop nor pause. The reason I don't use pause on the UI is that it may get confusing since we are not really pausing (in the sense that if I start playback again, it doesn't continue from the old place, like a DVR). If you prefer to not have the stop button, you have multiple choices: 
- Don't mark the stream as live
- Override the alias for the stop button to point to the pause button
- Add your own action
