### ISSUE TITLE
If the source video uri points to an empty page cast queue gets cleared

### ISSUE THREAD

**Issue by malsabbagh** [googlecast/CastCompanionLibrary-android#276]
I can put a workaround for this specific case but shouldn't CastCompanionLibrary just remove this one invalid entry from the queue instead of clearing it fully?

**Comment by malsabbagh** [comment]
Just to clarify the video uri is pointing to a page that returns a http 403 Forbidden error.

**Comment by naddaf** [comment]
No, that is not CCL's job to validate your URLs; you should catch that before adding the media item (on your sender side) or on the receiver side.

**Comment by naddaf** [comment]
Think about a case that you are providing a URL but in the  customData associated with the load command, you are also providing a token that is the "key" to access that URL and you send the URL and "token" to your receiver and your receiver knows how to use the token to access the URL (otherwise one would get a 403). How should CCL know that is the way you are providing access? Should it remove all your URLs since they give 403 if they are called with no "token"?  CCL shouldn't care about your URLs, it is a library that puts the urls that you provide together, in a queue and sends them over to your receiver, whether those are good or bad URLs.

**Comment by malsabbagh** [comment]
I don't disagree with who should validate the URL. But the real issue which could be a bug in CCL is that the CCL won't load any videos afterwards. 
So what happens:
1- The queue is cleared
2- queueLoad requests don't work anymore until we disconnect and connect again with the receiver. 

I guess what you are saying the library shouldn't worry about invalid URLs, but shouldn't it recover from invalid request without the need to reestablish the connection? Or does this still rely on the client of the CCL?

**Comment by naddaf** [comment]
It is not the CCL who clears the queue or anything of that sort, it is your receiver; I suggest you take a look at your receiver's log.

**Comment by malsabbagh** [comment]
I see, so this is on Styled Media Receiver end. I will have a look into that soon. Thanks for the info.
