### ISSUE TITLE
IntroductoryOverlay fails with Android Support Library 23.2

### ISSUE THREAD

**Issue by granoeste** [googlecast/CastCompanionLibrary-android#278]
update build.gradle
> ext {
>     supportLibVersion = '23.2.0'
>     versionName = '2.8.0'
> }

But, IntroductoryOverlay failed.

> android.view.InflateException: Binary XML file line #42: Error inflating class Button
>     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
>     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
>     at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:109)
>     at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:100)
>     at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:79)
>     at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay$Builder.build(IntroductoryOverlay.java:296)

How to solve this problem?

**Comment by naddaf** [comment]
Just tried 23.2.0 and didn't run into any issue.

**Comment by naddaf** [comment]
There seems to be an issue with KitKat with Widget.AppCompat.Button.Colored style (that is used in the Button element in the IntroductoryOverlay (see https://code.google.com/p/android/issues/detail?id=201817). Till that issue is resolved, we don't have much options except to remove the line style="@style/Widget.AppCompat.Button.Colored" from the Button in that layout. I am following up with the folks responsible for that support library to see what would the way forward.

**Comment by rhlff** [comment]
This is fixed with Support Library version 23.2.1, CastCompanionLibrary-android should also be updated to this version.

**Comment by naddaf** [comment]
Should be fixed in 2.8.3
