### ISSUE TITLE
CCL does not detect conection when using more than 1 process

### ISSUE THREAD

**Issue by kaoz70** [googlecast/CastCompanionLibrary-android#293]
Hello, I have 2 processes in my app, one for the main interface, and another one for the video player, both have the cast buttons installed. I have no problem casting and initiating activities within the "main" process, they show that the cast button as connected and do everything correctly. 

The problem begins when I initiate the player activity, which is in a "player" process and then close the player, the cast button in the returning activity (which is in the "main" process) is still detecting the cast device as disconnected. If I go into the player again, the button shows as connected. If I restart the App the "main" process activities detect the cast as connected (which is the correct behaviour)

I hope that makes sense.

What could the issue be?

**Comment by naddaf** [comment]
For cases that an apk has multiple processes, such as yours, unfortunately there is no simple out of the box solution to keep both processes stay in sync without you do extra custom work in your app to maintain that level of synchronization for the cast state. Being a corner and rare case, CCL doesn't attempt to address that.

**Comment by kaoz70** [comment]
Ok, thanks I understand now.

Could you point me in the right direction regarding the synchronization of the cast state? Ive tried intializing the CastConsumer on the onResume() method, maybe I should re initialize the VideoCastManager? I dont know what side effects that would have.

**Comment by naddaf** [comment]
Since I haven't worked with multi-process applications, I can't really give you any useful hint directly; I am guessing that once you connect to a cast device (or do/notice any other cast lifecycle changes) you need to persist that in a way that when the other process starts, it can read that persisted state and forces a synchronization in this new process; for example if there was a connection to a cast device in the first process, when the second process comes in, it has to connect to the same device, etc.
