### ISSUE TITLE
Disconnecting using the notification stops the application

### ISSUE THREAD

**Issue by jarnova** [googlecast/CastCompanionLibrary-android#300]
Disconnecting from the x on the notification calls stopApplication. The documentation for receiver apps states the following: 

> When the user selects to explicitly disconnect, the sender app should close the connection to the receiver and not stop the receiver application.

So shouldn't it be left to the receiver to decide whether we want to stop the application or not. If the user clicks stop casting in the app it doesn't call stopApplication so why is the notification control behaving in a different way?

**Comment by naddaf** [comment]
That is by design. The reason is that we want to provide a quick way for the user to stop the app and don't want him to be forced to first open the app and then take an action. If user wants to disconnect and not stop, then user can tap on the content of the notification to go to the app and then disconnect there.
