### ISSUE TITLE
IntroductoryOverlay button off screen.

### ISSUE THREAD

**Issue by cdilks** [googlecast/CastCompanionLibrary-android#303]
The nexus 10 in Landscape the button to close the overlay is below the nav buttons
![pasted image at 2016_05_10 10_13 am](https://cloud.githubusercontent.com/assets/3311822/15150609/ead88a18-169b-11e6-914d-3099a9318677.png)

**Comment by rhlff** [comment]
I experienced the same issue on tablet devices. On some of them the button is still on-screen, but on top of the system bar and not clickable.

**Comment by naddaf** [comment]
I don't have N10 but when run in emulator for N10, I am not seeing this issue in CastVideos-android app, here is a screenshot (I increased the radius of focus point of IntroOverlay to make it more clear for our purpose and allowed VideoBrowserActivity to be in landscape):

![device-2016-05-21-114103](https://cloud.githubusercontent.com/assets/355366/15450148/29c079b0-1f49-11e6-9aa3-d03db13cf07a.png)

I suggest you try CastVideos-android app and see if you can reproduce that.

**Comment by rhlff** [comment]
The issue appears when the system bar is at the bottom, not on the right.

**Comment by rhlff** [comment]
Here are two screenshots I took on a Nexus 9 emulator with CastVideos-android app and my app:
![pic1](http://i.imgur.com/m1eEuDV.png?1)
![pic2](http://i.imgur.com/FvIS7HX.png?1)

**Comment by naddaf** [comment]
You can control the margins for the button via resources; put the numbers that make sense for your app in the appropriate resource folder, specific to the size/orientation of your app (the following values are the default):
    <dimen name="ccl_intro_button_margin_right">12dp</dimen>
    <dimen name="ccl_intro_button_margin_bottom">10dp</dimen>

**Comment by rhlff** [comment]
Of course I could manipulate the placement of the button by myself. But this is not an app specific issue, it applies to usage of the CCL in general. Therefore, the library should take care that this button is placed correctly on all devices. If the overlay is used without customizations by default, it should not be necessary to overwrite the layout file in order to just fix this. It is not only an issue regarding cosmetics, the button is also not clickable in this cases even if it is still partly visible. The overlay can not be closed properly because of that.

**Comment by naddaf** [comment]
@rhlff In my earlier post, I hadn't surrounded the xml with proper quoting so it didn't show up properly. Below is the same thing with proper syntax: there are two resources specifically designed for that purpose and you can set the values for these based on what you feel is right; a safe approach is to put enough margins for ALL devices so that they are always away from edges no matter there is a nav bar or not (say setting 50dp from the bottom will be a safe value since bottom bar is 48dp). One may have a theme where the bottom bar is hidden (immersive mode) in which case it makes sense to have a smaller value and that is why the library cannot have a value that fits everyone's purpose. If you are not happy with this approach, you are welcome to write your own version of this feature and use that instead.
``` xml
<dimen name="ccl_intro_button_margin_right">12dp</dimen>
<dimen name="ccl_intro_button_margin_bottom">10dp</dimen>
```

**Comment by cdilks** [comment]
@naddaf My original concern wasn't even the spacing but sometimes the overlay is above, and sometimes it is below the system ui. When the button is lower on the screen (over the system ui) and it then loads the overlayview below the system ui, it prevents the user from being able to click the button. Why would it sometimes be above, and sometimes be below the system ui?

**Comment by naddaf** [comment]
It might be due to the different versions of framework, or themes; I haven't dug into it to see why that happens and since it works fine as long as the button is placed above the bottom bar, it shouldn't interfere with the functionality.
