### ISSUE TITLE
Support for callbacks on async operations

### ISSUE THREAD

**Issue by mariusgreve** [googlecast/CastCompanionLibrary-android#317]
Not using the CCL you can set a `ResultCallback` on the `PendingResult` returned by e.g. `remoteMediaPlayer.queueRemoveItems(...)` and then act on the success of the result, but CCL doesn't expose the `PendingResult` and thus I cannot register a `ResultCallback`.

I know that you kan register a `VideoCastConsumer` and override `onMediaQueueOperationResult(...)`, but that only gives a constant ID for the type of operation, not an actual unique ID of the operation so there is no way of knowing which exact operation it is a result for.﻿

Are there any solutions to this? The reason I'm asking is because I want to chain multiple operations. Let's say I want to first remove some items and then, only if the remove was successful I want to add some other items.

**Comment by naddaf** [comment]
As was mentioned in the earlier thread, there are callbacks that you can use to do what you want. Since these calls are asynchronous, "chaining" them simply means that you fire one, wait for the response and then fire the second one, etc. So for each call, as long as there is a callback, you should be able to manage the same. It sounded, from you other thread, that you were interested in queue operations. The callback onMediaQueueOperationResult(operationId, status) is the callback that can be used; you have a queue of operations that you want to perform (on a queue); you perform the first one, then monitor that callback, when you see a success for your operation, you grab the next operation and perform that, and so on. Even if you had access to the PendingIntent, you would have needed to do a very similar thing. And there is no ID involved in any of these; the pending result doesn't return an ID to you either.
