### ISSUE TITLE
Cast SDK v3.0.0 Support 

### ISSUE THREAD

**Issue by luckcoolla** [googlecast/CastCompanionLibrary-android#321]
Hey, 

I see the new sdk version has been released:
https://developers.google.com/cast/docs/release-notes#june-27-2016
    `compile 'com.google.android.gms:play-services-cast-framework:9.2.0'`
Are you going to update the CastCompanionLibrary with some new methods in the sdk_v3?

Thanks.

**Comment by naddaf** [comment]
Is there something missing in Cast SDK v3 that you would not want to use that directly instead of CCL?

**Comment by luckcoolla** [comment]
Sure, CCL give us the fastest and the easier way to integrate Cast functionality to the application. But as I see, sdk_v3 is mostly based on the CCL, is it right that CCL is going to be depricated since sdk_v3 has been released? 

Well, I've checked the [documentation](https://developers.google.com/cast/docs/reference/android/com/google/android/gms/cast/framework/package-summary) and the sample [app code](https://github.com/googlecast/CastVideos-android).

I see it will be hard for us to customize some elements like VideoMediaRouteControllerDialog (class name in the CCL) - we have improved your basic one with layout and additional buttons, UIMediaController(class in the new sdk). 

I'm still checking out new api, but I've not found how to work with the custom data channels. Previously there was one data channel implemented in the `VideoCastManager.attachDataChannel() {..}` and it calls listeners to handle the messages
             ```
   for (VideoCastConsumer consumer : mVideoConsumers) {
                    consumer.onDataMessageReceived(message);
                }
```
The default dataChannel has been observed mostly by VideoCastManager, for one channel we have to only implement the messages handler.

**Comment by naddaf** [comment]
The main goal for creating SDK v3 was to make it easier for developers to build cast-ready apps, including the needed UI elements, across all 3 platforms. CCL has been doing that for Android and in v3 of SDK, that is done as part of SDK, both for Android and iOS. A number of designs in v3 was inspired by CCL and the feedback that it collected. Moving forward, I will maintain CCL in a support mode: if bugs are found, I will try to address them but I will not add new functionality since the preferred approach should be SDK v3 now. I don't expect everyone migrate from CCL to v3 immediately (v3 will have a bigger impact on iOS since there was no equivalent of CCL for iOS) but at the same time, we like to understand if there are shortcomings on the v3 side that prevents folks from migration; those feedback will be appreciated and will be addressed as much as possible. So if you have reasons that you think migration to v3 is not easy or feasible for your app, please open Feature Requests on our SDK Issue Tracker so we can internally look at them and incorporate your feedback. 

That said, lets get back to your initial question. CCL is a wrapper around SDK v2 and SDK v3 is, in many ways, similar to that, in the sense that is basically a wrapper around SDK v2 (i.e. all APIs from v2 are still available but using v3 makes your life easier). It doesn't make sense for one wrapper (CCL) to use another wrapper (v3). In addition, CCL hides most of v2 and exposes new wrapped/enhanced/simplified APIs. Is there something specific in v3 that you needed and CCL doesn't provide that already?

**Comment by luckcoolla** [comment]
Thank you for explanation, now I see the picture.

No, at the moment I don't see anything in v3 that CCL doesn't provide.

**Comment by TR4Android** [comment]
@naddaf Is it still possible to fully customize the notification with Cast SDK v3? As far as I can see the new [MediaNotificationService](https://developers.google.com/android/reference/com/google/android/gms/cast/framework/media/MediaNotificationService) doesn't have a `buildNotification()` method that I can override.

**Comment by naddaf** [comment]
@TR4Android Your question is neither related to the original question in this issue, nor is related to CCL, so please direct your question to more appropriate places/forums.

**Comment by TR4Android** [comment]
@naddaf Thanks for the reply, but I'm still unsure where the correct place would be. Is https://code.google.com/p/google-cast-sdk/issues/list the correct issue tracker to put this in?

**Comment by naddaf** [comment]
Yes, if you believe there is a bug or if you have a feature request for SDK v3, please use that url. If you have a quick question like the one you asked here, post to official Cast Developer G+ community, thx.

**Comment by TR4Android** [comment]
@naddaf OK, thanks for clarifying this :+1:

**Comment by christoff** [comment]
@TR4Android did a feature request ever get created notification customization? i can't seem to find it.

**Comment by TR4Android** [comment]
@christoff No, I'm not aware of any feature request in the Google Cast issue tracker. Somebody else already had posted a question to the [Google+ Cast Developer community](https://plus.google.com/116492931465116034856/posts/XACY13hCtmn), but there was no helpful answer there. I've also created a [StackOverflow question](http://stackoverflow.com/questions/38972586/custom-notification-with-google-cast-sdk-v3) (which you've aready seen, it seems :wink:), again with no answer. So, as it is now, it does not seem as if Cast SDK v3 supports custom notifications.
@naddaf Maybe now is the time to create a feature request for this in the issue tracker?

**Comment by naddaf** [comment]
@TR4Android It would be helpful to include some info on the usecase that you have; why you need to have that level of customization, etc. The SDK team will look at the feature requests not me :-)
